#!/usr/bin/env bash
# This script finds the PID of ./4-to_infinity_and_beyond using pgrep

pgrep -af bash | while read -r pid cmd; do
    if [[ "$cmd" == *"./4-to_infinity_and_beyond"* ]]; then
        kill "$pid"
    fi
done
