#!/usr/bin/env bash
# This script kills the 4-to_infinity_and_beyond process
echo $$> /tmp/myscript.pid
delfunc()
{
	rm -f /tmp/myscript.pid
}
func1()
{
	echo "I hate the kill"
	delfunc
	exit
}


func2()
{
	echo "Y U no love me?!"
	delfunc
	exit
}
trap func1 SIGTERM

trap func2 SIGINT

while true
do
	echo "To infinity and beyond" 2>/dev/null
done
