#!/usr/bin/env bash
# This script kills the 4-to_infinity_and_beyond process
pid_file="/tmp/myscript.pid"

echo $$ > "$pid_file"

handle_sigterm() {
    echo "I hate the kill command"
    rm -f "$pid_file"
    exit 0
}

handle_sigint() {
    echo "Y U no love me?!"
}

handle_sigquit() {
    rm -f "$pid_file"
    exit 0
}

trap handle_sigterm TERM
trap handle_sigint INT
trap handle_sigquit QUIT

while true
do
    echo "To infinity and beyond"
    sleep 2
done
